### ISSUE TITLE
[Suggestion] Use absolute path for fonts directory

### ISSUE THREAD

**Issue by xfzv** [Mangeshrex/rxfetch#12]
https://github.com/Mangeshrex/rxfetch/blob/1877bb78f8238a1b2a26e554caad5a48604cecf9/rxfetch#L90

This will fail if the repository isn't cloned to `$HOME` directory.

```sh
cp -r ttf-material-design-icons/* $HOME/.local/share/fonts
```
would be better in my opinion.

**Comment by Mangeshrex** [comment]
Ok I'll do
