### ISSUE TITLE
Icons do not load

### ISSUE THREAD

**Issue by Yisus7u7** [Mangeshrex/rxfetch#16]
![Screenshot_20210624-014422](https://user-images.githubusercontent.com/64093255/123215820-8236b500-d48e-11eb-8ac0-2c9dfb1a29f7.png)
![Screenshot_20210624-014451](https://user-images.githubusercontent.com/64093255/123215824-82cf4b80-d48e-11eb-883f-ce8eb93fff58.png)

Hi, I use termux x11, copy the fonts to ~/.fonts and it doesn't work, why?

**Comment by Mangeshrex** [comment]
Is that a vps server? And you can try copying the fonts to ~/.local/share/fonts or in ~/.termux/fonts (if exists) or even /usr/share/fonts and alsov(rxfetch wasn't made for termux

**Comment by Yisus7u7** [comment]
No, it's not a vps, it's pure Android

**Comment by Yisus7u7** [comment]
I already tried changing the route and it still does not work 

```
~/extra/rxfetch $ ./rxfetch 
cp: cannot stat 'fonts/*': No such file or directory
```

**Comment by Mangeshrex** [comment]
Make a dir as ~/.termux/fonts or extra/fonts

**Comment by Yisus7u7** [comment]
![Screenshot_20210624-023055](https://user-images.githubusercontent.com/64093255/123221171-4868ad00-d494-11eb-93ce-8f3db158d255.png)

Ready, thanks, ps: is there a way to change that penguin for something else?

**Comment by Mangeshrex** [comment]
Umm nope not lately but am working on getting ASCII support.
