### ISSUE TITLE
pacman icons print too close to each other 

### ISSUE THREAD

**Issue by siduck76** [Mangeshrex/rxfetch#17]
pacman icons stick too close to each other now , there was better space before. Now it looks ugly :/ 

![image](https://user-images.githubusercontent.com/59060246/123231057-77633b00-d4f5-11eb-8042-af84bb68c8f3.png)

**Comment by Mangeshrex** [comment]
Hmm I'll change get back to the old placements xD btw I see you applied new colorscheme show wen?

**Comment by siduck76** [comment]
yea thats gruvbox material modified version for NvChad , gonna add some new theme to nvchad so using gruvchad for a while.

**Comment by Mangeshrex** [comment]
@siduck76 fixed it you can wget now

**Comment by siduck76** [comment]
> @siduck76 fixed it you can wget now

![image](https://user-images.githubusercontent.com/59060246/123260217-f2871a00-d512-11eb-9f67-94552733f278.png)


add spaces around pacman icons 

```echo -e "        ${c6}󰮯 ${c6}${c2} 󰊠 ${c2}${c4} 󰊠 ${c4}${c5} 󰊠 ${c5}${c7} 󰊠 ${c7}"
```

**Comment by Mangeshrex** [comment]
Ok I'll do

**Comment by Mangeshrex** [comment]
Done

**Comment by Mangeshrex** [comment]
Did you switch to gruvbox?

**Comment by siduck76** [comment]
idk If I switched , some wanted gruvbox for NvChad so making custom gruv theme for it so im staying on gruvbox for a while. doesnt look that bad 

![image](https://user-images.githubusercontent.com/59060246/123261080-f0718b00-d513-11eb-8a7d-d79b89fce98e.png)

**Comment by Mangeshrex** [comment]
Yup this looks ok but the old one was better

**Comment by siduck76** [comment]
yes Ik , this is just an additional theme for nvchad

**Comment by Mangeshrex** [comment]
Yes :D

**Comment by Mangeshrex** [comment]
Wen returning to tg?

**Comment by siduck76** [comment]
> Returning to tg?

no

**Comment by Mangeshrex** [comment]
Then when?

**Comment by Mangeshrex** [comment]
Oh k best of luck
