### ISSUE TITLE
Pacman icons

### ISSUE THREAD

**Issue by engjpacheco** [Mangeshrex/rxfetch#28]
Hi, i install from the aur repo via yay ,also the material fonts bit the icons doesn't properly appears. Any suggestions? Thanks in advance.

**Comment by Mangeshrex** [comment]
Can you show me the errors? Ig i know the error. so if your ~/ has a rxfetch git repo cd into that and then copy the downloads folder to `$PATH` and do `fc-cache -v`.

**Comment by engjpacheco** [comment]
I not move anything cause I installed it by yay -S rxfetch, and this is the issue:

![rxfetch](https://user-images.githubusercontent.com/77270456/135647360-879ac365-e3c6-4954-a161-4cb341c8d179.png)

**Comment by engjpacheco** [comment]
should I remove it and manually install it??

**Comment by Mangeshrex** [comment]
thanks :) so listen to me now 

do `fc-list | grep -i Material` if the output is similar to this  `/home/void/.local/share/fonts/ttf-material-design-icons/materialdesignicons-webfont (1).woff: Material Design Icons:style=Regular` then you dont need to install the fonts. just follow the readme wget step 

If you dont get anything like that remove the rxfetch from yay. and git clone this repository and follow the steps manually given in the readme.

**Comment by engjpacheco** [comment]
I remove it, and installit via git clone and the result is the same.

**Comment by Mangeshrex** [comment]
Bruh how is this possible can you show the output of fc-list command? 

This 
` fc-list | grep -i Material  `

**Comment by engjpacheco** [comment]
yes late I´ll, but y have the font installed, but i don´t know if the font of my terminal matters?

**Comment by Mangeshrex** [comment]
What terminal emulator it is? I doubt it might be st  but still that doesnt matter the font gets installed to the system

**Comment by engjpacheco** [comment]
yes it is st terminal, I will try delete it again, and try the wget mode, if not work, i´ll try with kitty, and see what happen.

**Comment by Mangeshrex** [comment]
Ok sure

**Comment by engjpacheco** [comment]
i try it all the ways, but nothing works, i dont knos why, I still use it anyways, is awesome. 

BUt one last thing, how I can find the pacman icons that you put in the script??
thank u so much.

**Comment by Mangeshrex** [comment]
Those are material design icons bruh. 

So, do a last try cause you might be doing something wrong for sure remove all the cloned directories and packages you installed for getting rxfetch and then do `git clone https://github.com/Mangeshrex/rxfetch` after doing this cd into rxfetch and do `cp ttf-material-design-fonts/ ~/.local/share/fonts && fc-cache -vf ` after doing this close te terminal restart it and cd into rxfetch directory and do `./rxfetch`.

**Comment by engjpacheco** [comment]
yeah, I do that, but don't work, I think maybe is a problem with my configuration, I don't know, I still used it anyways, I like the design. What I don't do is remove also the material fonts, I gonna try that....

and the icons, for example how can y type a pacman icon, or there is a cheat sheet for that ??, I am currently do some changes to my DWM and I put some of the pacman icons that u use in the rxfetch script,.

Thanks for responding !!

**Comment by Mangeshrex** [comment]
When Im on my laptop I'll send you the cheatsheet if I get that cuz material Dev's have updated something's

**Comment by engjpacheco** [comment]
Thank so much

**Comment by Mangeshrex** [comment]
https://pictogrammers.github.io/@mdi/font/5.3.45/ here it is

**Comment by engjpacheco** [comment]
I solve it adding the fonts into the fonts.conf files. thanks for the support!!!
