### ISSUE TITLE
Pacman Icons Missing From Gnome Terminal

### ISSUE THREAD

**Issue by pratirupm** [Mangeshrex/rxfetch#31]
![image](https://user-images.githubusercontent.com/45709214/141455417-9e88939f-5a76-4ab1-b692-4571f7cd89c7.png)

I tried Konsole and Alacrity too those were working perfectly fine. Do I have to do any special settings on gnome-terminal's side.

**Comment by Mangeshrex** [comment]
Speaking of gnome terminal. Those terminal emulators don't support multiple fonts. So try alacritty. If even alacritty doesn't work the fonts aren't properly installed on to your system. So install then properly

To check if it's installed or not do 
`fc-list | grep -i "Material"`

**Comment by pratirupm** [comment]
> Speaking of gnome terminal. Those terminal emulators don't support multiple fonts. So try alacritty. If even alacritty doesn't work the fonts aren't properly installed on to your system. So install then properly
> 
> To check if it's installed or not do `fc-list | grep -i "Material"`

Yeah its working on alacrity and konsole :'( I really loved this fetch but thanks regardless ^_^

**Comment by Mangeshrex** [comment]
👍
