### ISSUE TITLE
Fix font dir & update README

### ISSUE THREAD

**Issue by tuwuna** [Mangeshrex/rxfetch#32]
AUR: `cp: cannot stat 'ttf-material-design-icons/*': No such file or directory rxfetch`

Manual: Should be  `cp ttf-material-design-icons/* $HOME/.local/share/fonts` instead of `cp ttf-material-design-fonts/* $HOME/.local/share/fonts`

**Comment by Mangeshrex** [comment]
Updated the changes you suggested
