### ISSUE TITLE
Issue with displaying pkgs

### ISSUE THREAD

**Issue by MeliodasZoom** [Mangeshrex/rxfetch#33]
The pkgs number is not being displayed on Gentoo Linux. 

everything else works perfectly

here is an image:

![2021-11-19_12-47](https://user-images.githubusercontent.com/85227613/142571890-fa8bb845-802b-4caa-b917-554333fd6307.png)

**Comment by Mangeshrex** [comment]
Idk the reason why is it not working for you but a friend of mine got it working on a fresh Gentoo install.

![IMG_20211120_134842_346](https://user-images.githubusercontent.com/82205152/142719599-184abb99-ce59-4934-ad15-caa2fc60b080.png)

**Comment by alpheratz0** [comment]
Hi @MeliodasZoom, can you provide the output of this command?

```sh
bash -x $(which rxfetch) >/dev/null
```

**Comment by MeliodasZoom** [comment]
I actually found out the issue which is that I  have packages from both emerge and flatpaks which is the reason for it to show nothing. Now I have removed the flatpaks just to check it and it works well.

**Comment by Mangeshrex** [comment]
👍👍
