### ISSUE TITLE
Icons not showing in Konsole

### ISSUE THREAD

**Issue by Prayag2** [Mangeshrex/rxfetch#34]
Here's a screenshot:
![image](https://user-images.githubusercontent.com/39525869/145429098-e2d49817-7532-404b-bfaf-7016aa544e64.png)
I've installed ttf-material-design-icons in `~/.fonts/ttf-material-design-icons` and `/usr/share/fonts/ttf-material-design-icons` but it's still not working.

**Comment by Mangeshrex** [comment]
The foremost question I would like to ask is does konsole support multiple fonts?

**Comment by Prayag2** [comment]
I don't know :/

**Comment by 0n1cOn3** [comment]
> The first question I would like to ask is does konsole support multiple fonts? 

Yes! Of course. Im working with Konsole and Terminator. Both have multi font support.

**Comment by Mangeshrex** [comment]
> > The first question I would like to ask is does konsole support multiple fonts?
> 
> Yes! Of course. Im working with Konsole and Terminator. Both have multi font support.

Ohh ok so @Prayag2 
1. Do `fc-cache -vf` kill your terminal and restart and try if it works. 
2. If the first doesn't work, then do a `ls ~/.local/share/fonts` and check if that folder has `ttf-material-design-icons/` or material design icons file. If you find that file there present. Delete those files/folder. And then download the raw files of that from from ![here](https://GitHub.com/Mangeshrex/rxfetch/tree/main/ttf-material-design-icons), and place them in `~/.local/share/fonts`. Then restart terminal or do `fc-cache -vf` to generate the font cache

**Comment by Prayag2** [comment]
I tried it. It still doesn't work :(

**Comment by 0n1cOn3** [comment]
Thanks for your answer. I will investigate this issue and let you know when it is fixed.

**Comment by Prayag2** [comment]
Okay. Thank you for your time!

**Comment by Mangeshrex** [comment]
Is your fixed now?
