### ISSUE TITLE
OS name doesn't show

### ISSUE THREAD

**Issue by arionrefat** [Mangeshrex/rxfetch#35]
![image](https://user-images.githubusercontent.com/37513070/145519341-6daa700e-127e-433b-b90b-91a983094db2.png)
I use arcolinux, But it shows blank.

**Comment by arionrefat** [comment]
![image](https://user-images.githubusercontent.com/37513070/145519410-93cf2ae0-b1ea-4afb-be6f-3c7409b1f1db.png)

**Comment by Mangeshrex** [comment]
Weird issue could you please trying reinstall the script from scratch ?

**Comment by arionrefat** [comment]
okay, Wait

**Comment by arionrefat** [comment]
![image](https://user-images.githubusercontent.com/37513070/145590589-1a952093-ac48-4996-b3ed-0bba55d2d9af.png)
Nah, still shows same thing

**Comment by 0n1cOn3** [comment]
> Weird issue could you please trying reinstall the script from scratch ? 

Can't be that. It must be something with the script itself which does not run as wished in Arco Linux.

**Comment by 0n1cOn3** [comment]
It seems to be a Regex issue @Mangeshrex

**Comment by Mangeshrex** [comment]
> > Weird issue could you please trying reinstall the script from scratch ?
> 
> Can't be that. It must be something with the script itself which does not run as wished in Arco Linux.

Yeah right but other Arco users have might got it working right? I gotta ask some Arco guy for that.

**Comment by Mangeshrex** [comment]
> It seems to be a Regex issue @Mangeshrex

What do you mean by that?

**Comment by 0n1cOn3** [comment]
Yes. If it still persists, ping me in Telegram. I would then setup a arco vm to test it.

**Comment by Mangeshrex** [comment]
I'm off their I can't come. Can you please go to Arco Linux tg group and ask someone to test rxfetch on their sys? I'm sure some guy would help.

**Comment by 0n1cOn3** [comment]
> It seems to be a Regex issue @Mangeshrex 

As you see, as OS it does only show up a empty space and x86_64

**Comment by Mangeshrex** [comment]
> > It seems to be a Regex issue @Mangeshrex
> 
> As you see, as OS it does only show up a empty space and x86_64

Yes, maybe this is the issue itself

**Comment by 0n1cOn3** [comment]
> I'm off their I can't come. Can you please go to Arco Linux tg group and ask someone to test rxfetch on their sys? I'm sure some guy would help. 

I'm not in :/ Ah, we could talk asap when our Forum is back!

**Comment by Mangeshrex** [comment]
ahh F can you be active for a while on discord i wanted to ask about it.

**Comment by 0n1cOn3** [comment]
> ahh F can you be active for a while on discord i wanted to ask about it. 
> 
> 

Ya. Do you have my Discord Tag?

**Comment by Mangeshrex** [comment]
nope

**Comment by Mangeshrex** [comment]
i've messaged you check it

**Comment by 0n1cOn3** [comment]
K

**Comment by 0n1cOn3** [comment]
Got nothing. 

0n1cOn3#4075

**Comment by Mangeshrex** [comment]
I sent you message + friend req.

**Comment by Mangeshrex** [comment]
Try here `mangeshrex#3820`

**Comment by 0n1cOn3** [comment]
![image](https://user-images.githubusercontent.com/27576311/145592575-f7f5ecb2-1143-46d7-a392-1bd13b8cab42.png) 

I cant write you 🤣 We need to be friends.

**Comment by Mangeshrex** [comment]
whose gna accept lel

**Comment by arionrefat** [comment]
Another thing, I ran your get_OS function manually on my shell, it doesn't  return anything. I believe it's  with thr regex

**Comment by 0n1cOn3** [comment]
> Another thing, I ran your get_OS function manually on my shell, it doesn't  return anything. I believe it's  with the regex

I suspect it too.

**Comment by Mangeshrex** [comment]
> Another thing, I ran your get_OS function manually on my shell, it doesn't return anything. I believe it's with the regex

Hmm, you can break down the distro detect function part of the script and maybe try fixing it?

**Comment by arionrefat** [comment]
I can try lol,
also what this PRETTY_NAME variable do?
I dont seem to find any reference?

**Comment by arionrefat** [comment]
```cat /etc/os-release | grep 'NAME' | sed 's/NAME=//g'```

**Comment by arionrefat** [comment]
I solved it by this, but don't think that's the solution

**Comment by Mangeshrex** [comment]
Well done mate 👍

**Comment by Mangeshrex** [comment]
> I solved it by this, but don't think that's the solution

Why?
