### ISSUE TITLE
F: Filesystem suffix "create" is not applicable for --nofilesystem

### ISSUE THREAD

**Issue by 641mirhwl** [Mangeshrex/rxfetch#47]
### I'm getting F: Filesystem suffix "create" is not applicable for --nofilesystem 
![image](https://user-images.githubusercontent.com/93644076/167296897-11d78edf-841f-492d-9ac1-dbdff667e1d7.png)
- error occures with the command flatpak list

**Comment by 641mirhwl** [comment]
I'll just remove flatpak repos count

**Comment by alpheratz0** [comment]
Hi @641mirhwl,

what's the output of `which flatpak`?
