### ISSUE TITLE
pgrep -m errors

### ISSUE THREAD

**Issue by lumikalt** [Mangeshrex/rxfetch#48]
In the script step where it checks for the dw/wm, calling pgrep-m errors, as it does not appear to be a valid flag. Instead, it prints the usage help for pgrep. Maybe I need another version?

Using fish on kitty, in EndeavourOS.

**Comment by Mangeshrex** [comment]
Yes trying updating to latest version of pgrep

**Comment by lumi-kalt** [comment]
I'm running the latest, still shows no -m flag support...

**Comment by owl4ce** [comment]
Indeed. Procps-ng `pgrep`(1) doesn't have the `-m` flag, which most Linux distributions use. So, I was wondering which version of `pgrep` it's ..

**Comment by lumi-kalt** [comment]
The man-page says it's from 2020-06-04, don't know if that's when it was created or last updated

**Comment by owl4ce** [comment]
I guess the `-m` flag is like GNU `grep` `-max-count` flag (?)

https://github.com/Mangeshrex/rxfetch/blob/3960865a001c82e3321f0fcc1583787b3e9953d3/rxfetch#L185

```
 -m NUM, --max-count=NUM
              Stop  reading  a  file  after  NUM  matching lines.  If the input is standard input from a regular file, and NUM matching lines are output, grep ensures that the
              standard input is positioned to just after the last matching line before exiting, regardless of the presence of trailing context lines.  This enables  a  calling
              process  to  resume a search.  When grep stops after NUM matching lines, it outputs any trailing context lines.  When the -c or --count option is also used, grep
              does not output a count greater than NUM.  When the -v or --invert-match option is also used, grep stops after outputting NUM non-matching lines.
```

**Comment by owl4ce** [comment]
If your distro uses procps-ng, simply remove the `-m` flag. It should only show one process.

**Comment by lumi-kalt** [comment]
i see, ty

**Comment by Mangeshrex** [comment]
Is the issue fixed @lumi-kalt ?

**Comment by lumi-kalt** [comment]
Indeed. Tho I'm unsure if you can test pgrep's availability of the -m flag for everyone…

**Comment by owl4ce** [comment]
I suggest to use `ps -e | grep -m1 -Fo` instead.

https://github.com/Mangeshrex/rxfetch/blob/3960865a001c82e3321f0fcc1583787b3e9953d3/rxfetch#L185

**Comment by lumi-kalt** [comment]
Indeed, grep should work the same on all machines.
