### ISSUE TITLE
Pacman Icons not showing up

### ISSUE THREAD

**Issue by Ruturajn** [Mangeshrex/rxfetch#49]
Hi,
I know you have answered this issue multiple times, and I looked through all of them, but still could not get it to work. As you may have figured from the title, the pacman icons are not showing up in my terminal.

I am using Ubuntu 20.04 with qtile, and the terminal is Alacritty. You can see the screenshot below,

![image](https://user-images.githubusercontent.com/56625259/170022520-f5e5793f-4fb5-4e84-94f2-ad103e0ffa81.png)

Funny thing is they do show up in vim, when I open the rxfetch script,

![image](https://user-images.githubusercontent.com/56625259/170022677-c9559663-1fe4-43f7-bf83-629db9e5bc9b.png)

I really don't understand where I am making a mistake, the fonts are all placed in the proper directories. I have tried restarting the terminal many times, and also tried rebooting my Laptop, but the icons still do not show up. So, could you help me out with this?

Thanks

**Comment by Mangeshrex** [comment]
In your alacritty config set 1 font to material design, like you have to set 1st font (regular) as the word font and other than that you can set any other font to Material design icons. 

To find the appropriate font name do 
`fc-list | grep -8 "material" `
After getting the output copy paste the name of your and then add it to your config.

Regenerate font cache. 
`fc-cache -vf` 

And restart terminal

**Comment by Ruturajn** [comment]
Ok, Thanks, I will try it out and let you know.

**Comment by Ruturajn** [comment]
Hi,
I am closing this issue since it's been a long time.
Thanks
