### ISSUE TITLE
Custom font (pseudo error?)

### ISSUE THREAD

**Issue by JukoiDev** [Mangeshrex/rxfetch#50]
rxfetch shows an error message, but i have the font.
![image](https://user-images.githubusercontent.com/79868869/180604796-3a4e473e-199a-4b08-93cf-908440ab9572.png)

**Comment by Mangeshrex** [comment]
did you install the font properly ? 
as per the instructions given in the readme?

**Comment by JukoiDev** [comment]
Yes, and the pacman icons are there.

**Comment by Mangeshrex** [comment]
edit the script and dodge that error lol

**Comment by Mangeshrex** [comment]
FIxed?

**Comment by proffapt** [comment]
looks like an incomplete cloning, doesn't makes sense otherwise

**Comment by rocktimsaikia** [comment]
Add `~/.local/share/fonts` in `/etc/fonts/fonts.conf` like below. This font path is not listed by default with `fc-list` (at least in Ubuntu afaik). You have to add it manually.
```html
 <dir>~/.local/share/fonts</dir>
```
