### ISSUE TITLE
restricted environment

### ISSUE THREAD

**Issue by polluks** [Mangeshrex/rxfetch#52]
How about more `Unknown` fallbacks?
```
               os     Debian GNU/Linux 8 (jessie) x86_64
               ker    4.15.18-30-pve
     •_•       pkgs   Unknown
     oo|       sh     bash
rxfetch: line 162: free: command not found
    / '\'      ram
rxfetch: line 46: pidof: command not found
cut: /proc/1/comm: No such file or directory
   (\_;/)      init
rxfetch: line 167: uptime: command not found
               up
rxfetch: line 156: df: command not found
               disk

        󰮯  󰊠  󰊠  󰊠  󰊠

**Comment by Mangeshrex** [comment]
What distro are you using ?

**Comment by Mangeshrex** [comment]
Hella weird

**Comment by proffapt** [comment]
seems like non GNU version of these tools.

**Comment by proffapt** [comment]
@Mangeshrex if Debian, has these issues ( #51  ) these might be solved by using the macos compatibility (#53 ) on debian too. like just adding $kernel == debian

**Comment by Mangeshrex** [comment]
@polluks 

> @Mangeshrex if Debian, has these issues ( #51 ) these might be solved by using the macos compatibility (#53 ) on debian too. like just adding $kernel == debian
@polluks try this.

**Comment by polluks** [comment]
I suppose it's not Debian-specific, I have simply no access to /proc and so on.

**Comment by proffapt** [comment]
> I suppose it's not Debian-specific, I have simply no access to /proc and so on.

well that explains why

**Comment by proffapt** [comment]
And clearly since this issue is not related to the script - it's related to user's environment, it better be closed.
