### ISSUE TITLE
MacOS Pending tasks

### ISSUE THREAD

**Issue by proffapt** [Mangeshrex/rxfetch#54]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/86282911/194718221-c863c408-9743-4d06-8cd9-1adf697aa163.png">

**Wasn't able to**

- [ ] Get those pacman and ghosts working.
- [ ] Get a pacman-apple for macos.

in the MR #53

**Comment by proffapt** [comment]
@Mangeshrex assign this to me :)
Will be grateful for inputs from others and will also provide whatever I found to them too.. so don't hesitate to reach me out ;)

**Comment by polluks** [comment]
My output
```
./rxfetch 2>/dev/null
               
               os     macOS Darwin 13.0 arm64
               ker    22.1.0
     •_•       pkgs   -1, 234 brews (218 formulas & 16 casks)
     oo|       sh     zsh
    / '\'      ram    
   (\_;/)      init   launchd
               de/wm  unknown
               up    
               disk

**Comment by proffapt** [comment]
> My output
> ```
> ./rxfetch 2>/dev/null
>                
>                os     macOS Darwin 13.0 arm64
>                ker    22.1.0
>      •_•       pkgs   -1, 234 brews (218 formulas & 16 casks)
>      oo|       sh     zsh
>     / '\'      ram    
>    (\_;/)      init   launchd
>                de/wm  unknown
>                up    
>                disk   
> 

pkgs > most probably you don't have Mac ports installed, but that should have worked in this case too.

Rest should also work because they are pre installed tools for system management in macos

**Comment by proffapt** [comment]
@polluks can you show me the output to
>uptime

And 

> df -Hl | grep -w "/" | awk '{print $2}'

**Comment by proffapt** [comment]
Haven't tested on macOS Ventura tho, but those coreutils must not change with it anyways

**Comment by polluks** [comment]
```sh
$ uptime
21:55  up 1 day,  5:16, 3 users, load averages: 6,70 6,65 7,18
$ df -Hl | grep -w "/" | awk '{print $2}'
446G

**Comment by polluks** [comment]
My current output
```
               os     macOS Darwin 13.2 arm64
               ker    22.3.0
     •_•       pkgs   250 brews (232 formulas & 18 casks)
     oo|       sh     zsh
./rxfetch: line 201: -1: substring expression < 0
    / '\'      ram    
   (\_;/)      init   launchd
               de/wm  unknown
./rxfetch: line 211: -1: substring expression < 0
               up    
./rxfetch: line 189: -1: substring expression < 0
               disk

**Comment by proffapt** [comment]
@polluks I am on the same version of macos and it works for me.

Share the output of these commands again..
```sh
                df -Hl | grep -w "/" | awk '{print $2}'
                 df -Hl | grep -w "/" | awk '{print $4}'
````

**Comment by polluks** [comment]
`zsh rxfetch` works fine but no `./rxfetch`!

**Comment by proffapt** [comment]
> `zsh rxfetch` works fine but no `./rxfetch`!
@proffapt so an interactive check is not sufficient

What do you mean by interactive check?
Mhmmmm I got something which can be the issue, will check when i get on my rig

**Comment by proffapt** [comment]
> It seems to be a bash 3.2 incompatibility. It works in an interactive zsh but bash fails.

Exactly that's what I thought.. it is using older version as well as the BSD version.

**Comment by proffapt** [comment]
> > It seems to be a bash 3.2 incompatibility. It works in an interactive zsh but bash fails.
> 
> Exactly that's what I thought.. it is using older version as well as the BSD version.

That is indeed because of old BSD version of bash, it is recommended to use latest GNU version, preferably installed using Homebrew.

**Comment by proffapt** [comment]
Out of my interest now, closing it as not planned
