### ISSUE TITLE
Feature Request: `getopts`

### ISSUE THREAD

**Issue by proffapt** [Mangeshrex/rxfetch#55]
This is just a remainder for me and notifications for others; I am working(in my free time) ~rarely~ on implementing `getopts` feature, that is:

`rxfetch -okpu` prints only os, kernel, packages and uptime along with the **pacman-linux**

Obviously it was easy without the **pacman-linux** but what about doing this along with it?

**Comment by proffapt** [comment]
@Mangeshrex assign this to me :)

**Comment by Mangeshrex** [comment]
you can mess up with the script on the getopts branch created.

**Comment by proffapt** [comment]
This is a nightmare to do :)
